### PR TITLE
Fixed #93: servername was not supplied to TLS cfg

### LINKED ISSUE #93: TLS server name not set when hostInCertificate not set
**Describe the bug**
I have issues with connecting to a MSSQL server using TLS. I get the error

```
could not ping db	{"error": "TLS Handshake failed: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"}
```

**To Reproduce**
using a connection string comparable to this:
```
sqlserver://someuser:somepass@somehost?TrustServerCertificate=false&encrypt=true
```
and the code
```
db, err := sqlx.Open("sqlserver", connectionString)
db.Ping()
```
I get the error shown above.

The issue can be reproduced by this test (add it to `msdsn/conn_str_test.go`)

```
func TestServerNameInTLSConfig(t *testing.T) {
	connStr := "sqlserver://someuser:somepass@somehost?TrustServerCertificate=false&encrypt=true"
	cfg, err := Parse(connStr)
	if err != nil {
		t.Errorf("Could not parse valid connection string %s: %v", connStr, err)
	}
	if cfg.TLSConfig.ServerName != "somehost" || cfg.Host != "somehost" {
		t.Errorf("Expected somehost as host %s and TLS server, but got %s", cfg.Host, cfg.TLSConfig.ServerName)
	}
}
```

**Expected behavior**
`db.Ping()` works

**Additional context**
I think the bug was introduced in  fd440036dc0010d3437264a282e3e7b8b530cd50 

The [code for setting `p.Host`](https://github.com/microsoft/go-mssqldb/commit/fd440036dc0010d3437264a282e3e7b8b530cd50#diff-2c8ad7a8cbc93a80bee6b50de9c427c98c6aaa7085c16ccf7b01227fdd9a3863L143) was moved down in the parse function, resulting in an empty `p.Host` value at the time of the creation of `p.TLSConfig`.

### PR DESCRIPTION
**Pull request by jwbargsten**
A change in fd44003 moved the code for setting p.Host down in the parse function, resulting in an empty p.Host value at the time of the creation of p.TLSConfig. I extracted the TLS parsing into a separate function and moved the TLSConfig creation to the end of the parsing function.

closes #93

### CODE REVIEW

**Comment by jwbargsten** [comment]
@microsoft-github-policy-service agree

File: msdsn/conn_str.go [hunk 1]
```diff
@@ -651,16 +659,6 @@ func normalizeOdbcKey(s string) string {
 	return strings.ToLower(strings.TrimRightFunc(s, unicode.IsSpace))
 }
 
-const defaultServerPort = 1433
-
-func resolveServerPort(port uint64) uint64 {
```
Comment (jwbargsten) [inline msdsn/conn_str.go:656]: my IDE flagged it as "unused", so I applied "The Boy Scout Rule"

File: msdsn/conn_str.go [hunk 2]
```diff
@@ -113,6 +114,49 @@ func SetupTLS(certificate string, insecureSkipVerify bool, hostInCertificate str
 	return &config, nil
 }
 
+// Parse and handle encryption parameters. If encryption is desired, it returns the corresponding tls.Config object.
+func parseTLS(params map[string]string, host string) (Encryption, *tls.Config, error) {
+	var trustServerCert = false
```
Comment (shueybubbles) [inline msdsn/conn_str.go]: >var trustServerCert = false [](http://example.com/codeflow?start=1&length=27)

As a relative Go newbie I am curious whether 
there is a strong community bias for 
`x := val`
or
`var x = val` 
in particular situations.

File: msdsn/conn_str.go (hunk 1 above)
Comment (shueybubbles) [reply msdsn/conn_str.go:656]: yeah it moved to protocol.go thx

File: msdsn/conn_str_test.go [hunk 3]
```diff
@@ -217,6 +217,17 @@ func TestConnParseRoundTripFixed(t *testing.T) {
 	}
 }
 
+func TestServerNameInTLSConfig(t *testing.T) {
```
Comment (shueybubbles) [inline msdsn/conn_str_test.go:220]: >tServerNa [](http://example.com/codeflow?start=8&length=9)

can you add a variation using hostnameincertificate as well? I don't see any msdsn tests using it, just a tds test.

**Comment by shueybubbles** [comment]
thx for opening the issue and PR!

**Comment by shueybubbles** [comment]
pls update CHANGELOG.md . I will include this fix in the next tag

**Review by shueybubbles — CHANGES_REQUESTED** [review]
:clock1:

File: msdsn/conn_str.go (hunk 2 above)
Comment (jwbargsten) [reply msdsn/conn_str.go]: hey, I thought I was the go newbie ;)

I'm not sure myself. When I look at https://google.github.io/styleguide/go/best-practices#vardeclinitialization , it practically does not matter, but the short version is preferred if there is a non-zero value.

Comment (jwbargsten) [reply msdsn/conn_str.go]: so I'll fix it

**Comment by jwbargsten** [comment]
addressed the comments

File: msdsn/conn_str.go (hunk 2 above)
Comment (jwbargsten) [reply msdsn/conn_str.go]: the `var encryption Encryption` I could not change to a short version, because of type inference issues.

File: msdsn/conn_str_test.go [hunk 4]
```diff
@@ -217,6 +217,25 @@ func TestConnParseRoundTripFixed(t *testing.T) {
...
+
+	var tests = []struct {
+		dsn  string
+		host string
+	}{
+		{"sqlserver://someuser:somepass@somehost?TrustServerCertificate=false&encrypt=true", "somehost"},
+		{"sqlserver://someuser:somepass@somehost?TrustServerCertificate=false&encrypt=true&hostnameincertificate=someotherhost", "someotherhost"},
```
Comment (shueybubbles) [inline msdsn/conn_str_test.go]: >true& [](http://example.com/codeflow?start=80&length=5)

if encrypt isn't set, what should cfg.Host be? is using `encrypt=DISABLED&hostnameincertificate=something` 
or
`encrypt=false&hostnameincertificate=something` 

undefined options?

Comment (jwbargsten) [reply msdsn/conn_str_test.go]: hmm, tricky. I added tests that restore the previous logic. This means:

```
encrypt = DISABLED -> tls.Config is nil
encrypt = false -> empty tls.Config, but with hostname set
```

I'm not sure what the right logic would be, but in case of doubt, I would stick to the previous logic to stay backwards compatible.

Comment (jwbargsten) [reply msdsn/conn_str_test.go]: alternatively we could make it an error if one supplies `hostnameincertificate` and encrypt is not true.

Comment (shueybubbles) [reply msdsn/conn_str_test.go]: backward compatible is fine for now.
Once we branch a v2 we'll revisit it as part of the "TDS8" implementation.
Note that ADO.Net just ignores the property when Encrypt is not "Mandatory" or "Strict"
https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.hostnameincertificate?view=sqlclient-dotnet-standard-5.1

**Review by shueybubbles — APPROVED** [review]
:shipit:

File: msdsn/conn_str_test.go (hunk 4 above)
Comment (jwbargsten) [reply msdsn/conn_str_test.go]: Yeah, probably a good idea to refactor this stuff for v2. I also saw a 2nd definition of the encrypt enum which should be merged into one.

Anyway, thanks for approving. As I lack write access, I guess you or one of the maintainers has to merge it.
