### PR TITLE
fix: Added multisubnetfailover option, set to false to prevent issue #158

### LINKED ISSUE #158: Connection Error 17830 logged to extended events when connecting to servers with multiple IPs
**Describe the bug**

When using the library to connect to a VM with multiple IPs, SQL Server logs error 17830.  This may lead people to falsely believe there are network issues with the SQL instance. 

The 17830 error is logged due to a "fire and forget" pattern in the client library rather than network issues.

This go-mssqldb library defaults to a behavior that is similar to libraries where "multisubnetfailover" set to true.  The library attempts to connect to all registered IPs simultaneously but when the first successful connection is made, the library abruptly closes other connections without doing any work.  

SQL Server detects that as a "fire and forget pattern" and reports it as a 17830 error severity 20 state 11.  From the database engine's perspective it seems that something attempted a connection but it failed.  

You can reproduce via telnet by connecting on the appropriate port and disconnecting.   The error will log in extended events.

Network error code 0x2746 occurred while establishing a connection; the connection has been closed. This may have been caused by client or server login timeout expiration

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.
Configure a SQL Instance that listens on multiple registered IPs.  Connect and observe extended events.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

**Expected behavior**
Client gives an option to disable the multisubnetfailover like behavior to avoid false errors.

### Further technical details
SQL Server version: tested on SQL 2019
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container): tested on windows
Table schema: Schema is irrelevant 

**Additional context**

### PR DESCRIPTION
**Pull request by abairmj**
Fixes #158 if the connection string sets multisubnetfailover to false.  

I believe most other libraries default this to false but to prevent a breaking change I kept the current behavior (defaulted to true).

### CODE REVIEW

**Comment by abairmj** [comment]
@microsoft-github-policy-service agree

File: protocol.go [hunk 1]
```diff
@@ -85,11 +85,26 @@ func (t tcpDialer) DialSqlConnection(ctx context.Context, c *Connector, p *msdsn
 	} else {
 		ips = []net.IP{ip}
 	}
-	if len(ips) == 1 {
-		d := c.getDialer(p)
-		addr := net.JoinHostPort(ips[0].String(), strconv.Itoa(int(resolveServerPort(p.Port))))
-		conn, err = d.DialContext(ctx, "tcp", addr)
-
+	if len(ips) == 1 || !p.MultiSubnetFailover {
+<<<<<<< HEAD
```
Comment (shueybubbles) [inline protocol.go]: diff is showing merge conflicts

File: protocol.go [hunk 2]
```diff
@@ -85,11 +85,16 @@ func (t tcpDialer) DialSqlConnection(ctx context.Context, c *Connector, p *msdsn
 	} else {
 		ips = []net.IP{ip}
 	}
-	if len(ips) == 1 {
-		d := c.getDialer(p)
-		addr := net.JoinHostPort(ips[0].String(), strconv.Itoa(int(resolveServerPort(p.Port))))
```
Comment (shueybubbles) [inline protocol.go:90]: >resolveServerPort(p.Port) [](http://example.com/codeflow?start=61&length=25)

call `Itoa(resolveServerPort)` just once

File: protocol.go [hunk 3]
```diff
@@ -85,11 +85,16 @@ func (t tcpDialer) DialSqlConnection(ctx context.Context, c *Connector, p *msdsn
...
-		conn, err = d.DialContext(ctx, "tcp", addr)
-
+	if len(ips) == 1 || !p.MultiSubnetFailover {
+		// Try to connect to IPs sequentially until one is successful per MultiSubnetFailover false rules
+		for _, ipaddress := range ips {
+			d := c.getDialer(p)
+			addr := net.JoinHostPort(ipaddress.String(), strconv.Itoa(int(resolveServerPort(p.Port))))
+			conn, err = d.DialContext(ctx, "tcp", addr)
+			if err == nil {
```
Comment (shueybubbles) [inline protocol.go:97]: >if err == nil { [](http://example.com/codeflow?start=3&length=15)

Is there a difference in how errors from the multiple dial attempts are reported?
Does the error channel approach in the parallel implementation return an `error` object that aggregates all the parallel dial errors? If so, it may be desirable to perform a similar aggregation in the serial case.
 #Resolved

Comment (shueybubbles) [reply protocol.go:97]: my quick hack implies that the parallel model would seemingly return a single random dial error from the list.

eg this sample just prints "2"

```go
package main

import (
 "fmt"
)

func main() {
 errChan := make(chan error, 2)
 go func() {
  errChan <- fmt.Errorf("1")
 }()
 go func() {
  errChan <- fmt.Errorf("2")
 }()
 var err error
 select {
 case err = <-errChan:
 }
 fmt.Println(err.Error())

}
```

**Review by shueybubbles — APPROVED** [review]
:shipit:

File: protocol.go (hunk 2 above)
Comment (abairmj) [reply protocol.go:90]: Good call!  Will mod!  Thanks
