### PR TITLE
fix: support nullable types for bulkcopy

### LINKED ISSUE #190: BulkImport no longer supports Nullable types
**Describe the bug**
Since upgrading from v1.7.0 to v1.7.1, the `bulkimport` function no longer supports nullable types. I receive the following error when attempting to import:

```
bulkcopy: mssql: invalid type for float column: sql.NullFloat64{%!s(float64=0) %!s(bool=true)}
```

I believe this issue was introduced following the changes made in pull request #179. I am willing to create a PR to address and fix this issue if needed.

### PR DESCRIPTION
**Pull request by vecknishwaran**
Fixes #190

### CODE REVIEW

File: bulkcopy_test.go [hunk 1]
```diff
@@ -69,6 +69,7 @@ func TestBulkcopy(t *testing.T) {
 		{"test_geom", geom, string(geom)},
 		{"test_uniqueidentifier", uid, string(uid)},
 		{"test_nulluniqueidentifier", nil, nil},
+		{"test_nullfloat", sql.NullFloat64{Float64: 64, Valid: true}, 64.0},
```
Comment (shueybubbles) [inline bulkcopy_test.go]: >.NullFlo [](http://example.com/codeflow?start=24&length=8)

do we need any other sql.Nullxxx cases for completeness?

File: bulkcopy.go [hunk 2]
```diff
@@ -323,6 +324,19 @@ func (b *Bulk) makeParam(val DataValue, col columnStruct) (res param, err error)
 		return
 	}
 
+	switch valuer := val.(type) {
```
Comment (shueybubbles) [inline bulkcopy.go:322]: >switch valuer := [](http://example.com/codeflow?start=1&length=16)

should this switch be invoked after the switch instead of before it? Is there no implementation of `Valuer` that's not already handled directly by the switch?

File: bulkcopy_test.go (hunk 1 above)
Comment (shueybubbles) [reply bulkcopy_test.go]: add a case for `Valid: false`

File: bulkcopy.go [hunk 3]
```diff
@@ -323,6 +324,19 @@ func (b *Bulk) makeParam(val DataValue, col columnStruct) (res param, err error)
...
+	case driver.Valuer:
+		// If the value has a non-nil value, call MakeParam on its Value
+		val, e := driver.DefaultParameterConverter.ConvertValue(valuer)
+		if e != nil {
+			err = e
+			return
+		}
+		if val != nil {
+			return b.makeParam(val, col)
+		}
```
Comment (shueybubbles) [inline bulkcopy.go:332]: else?

**Comment by vecknishwaran** [comment]
@microsoft-github-policy-service agree company="FRG"

**Comment by vecknishwaran** [comment]
Hey, after further investigation, I think reverting the changes in `convertInputParameter` might be a better solution. I understand that you intended to bypass the `uniqueidentifier` types, so I included them in that section instead. I might be misunderstanding something, so please let me know if there's another reason for the current implementation.

**Review by shueybubbles — APPROVED** [review]
