### PR TITLE
Connection not closed when database name is incorrect #173 fix

### LINKED ISSUE #173: connection not closed when database name is incorrect
Opened same issue in original over at https://github.com/denisenkom/go-mssqldb/issues/798 and found this fork which seems to be more active however upon updating the package looks like the issue exists with this package as well

**Describe the bug**

If a database name is provided that does not exist, we get back an error however even though `db.Close()` is executed the network connection still remains open.

**To Reproduce**

```golang
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"os/signal"

	_ "github.com/microsoft/go-mssqldb"
)

func main() {
	var (
		username = "sa"
		password = "Password123"
		hostname = "127.0.0.1"
		port     = 1433
		database = flag.String("db", "master", "database name")
		count    = flag.Int("count", 1, "number of calls to make to the database")
	)

	flag.Parse()

	dsn := fmt.Sprintf("sqlserver://%s:%s@%s:%d?database=%s", username, password, hostname, port, *database)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	for i := 0; i < *count; i++ {
		if err := doQuery(ctx, dsn); err != nil {
			fmt.Println("error running query", i+1, err.Error())
		} else {
			fmt.Printf("run %d done\n", i+1)
		}
	}
	fmt.Println("waiting for ctrl+c to exit")
	<-ctx.Done()
}

func doQuery(ctx context.Context, dsn string) error {
	db, err := sql.Open("sqlserver", dsn)
	if err != nil {
		return fmt.Errorf("error open db %w", err)
	}
	defer db.Close()

	row := db.QueryRowContext(ctx, "SELECT 1")
	var result int
	if err := row.Scan(&result); err != nil {
		return fmt.Errorf("error scanning row %w", err)
	}

	return nil
}
```

If you provide a database name that exists then should see the following, before sending the exit signal if you look for connections to the database it will be in `TIME_WAIT`

```bash
❯ go run main.go -db exists
run 1 done
waiting for ctrl+c to exit

# new terminal
❯ netstat -an | grep '1.1433'
tcp4       0      0  127.0.0.1.60859        127.0.0.1.1433         TIME_WAIT
```

However if you provide a database name that does not exist then the connection remains `ESTABLISHED` even though it should have been closed.

```bash
❯ go run main.go -db unknown
error running query 1 error scanning row mssql: login error: Cannot open database "unknown" that was requested by the login. Using the user default database "master" instead.
waiting for ctrl+c to exit

# new terminal
❯ netstat -an | grep '1.1433'
tcp4       0      0  127.0.0.1.1433         127.0.0.1.60894        ESTABLISHED
tcp4       0      0  127.0.0.1.60894        127.0.0.1.1433         ESTABLISHED
```

**Expected behavior**
The network connection should be closed

### Further technical details
SQL Server version: docker image mcr.microsoft.com/mssql/server:2022-latest
Operating system: macOS 13.6.3

### PR DESCRIPTION
**Pull request by parMaster**
#173 describes a bug when a database name is provided that does not exist, but the connections remain open and db.Close() doesn't help to close them. 
This PR is supposed to fix this issue by closing connection before returning error. The connection is unusable despite the message from the server like `Cannot open database "shmaster" that was requested by the login. Using the user default database "master" instead` - db.PingContext returns an error, but connections remain open

### CODE REVIEW

**Comment by shueybubbles** [comment]
thx for the PR

Please add a test that fails without your change.

**Comment by parMaster** [comment]
> thx for the PR
> 
> Please add a test that fails without your change.

You're right.
As you can see in the original issue, we can monitor the opened connections with a `netstat -an | grep '1.1433'` cmd, but I think it's not right to call `exec.Command("netstat", "-an")` and check the output.
So, I've decided to query a `sys.dm_exec_connections` system view which [Returns information about the connections established to this instance of the database engine](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-connections-transact-sql?view=sql-server-ver16) and check if there are leaked connections left even after explicit `conn.Close()`.
The test fails without my change and shows the number of leaked connections.

File: tds_test.go [hunk 1]
```diff
@@ -694,6 +694,52 @@ func TestBadCredentials(t *testing.T) {
...
+	if err != nil {
+		t.Fatal("Open connection failed:", err.Error())
+	}
+	err = goodConn.Ping()
+	if err != nil {
+		t.Fatal("Ping with good credentials should not fail, but got error:", err.Error())
+	}
+	// Remember the number of open connections, excluding the current one
+	var openConnections int
+	err = goodConn.QueryRow("SELECT COUNT(*) AS openConnections FROM sys.dm_exec_connections WHERE session_id!=@@SPID").Scan(&openConnections)
```
Comment (shueybubbles) [inline tds_test.go]: some folks have to run the tests against shared servers. Can you capture the `local_net_address` value from the `goodConn`'s SPID and limit the search to rows that match it?

Comment (parMaster) [reply tds_test.go]: sure, good point

File: tds_test.go [hunk 2]
```diff
@@ -694,6 +694,59 @@ func TestBadCredentials(t *testing.T) {
...
+	if err != nil {
+		t.Fatal("Open connection failed:", err.Error())
+	}
+	err = goodConn.Ping()
+	if err != nil {
+		t.Fatal("Ping with good credentials should not fail, but got error:", err.Error())
+	}
+
+	var localNetAddr string
+	err = goodConn.QueryRow("SELECT local_net_address FROM sys.dm_exec_connections WHERE session_id=@@SPID").Scan(&localNetAddr)
```
Comment (shueybubbles) [inline tds_test.go:713]: you need an `ISNULL` on local_net_address to return an empty string or use one of the nullable types for the scan.

**Comment by parMaster** [comment]
@microsoft-github-policy-service agree company="Amoniac OÜ"

File: tds_test.go [hunk 3]
```diff
@@ -694,6 +694,62 @@ func TestBadCredentials(t *testing.T) {
...
+	if err != nil {
+		t.Fatal("Ping with good credentials should not fail, but got error:", err.Error())
+	}
+
+	var localNetAddr sql.NullString
+	err = goodConn.QueryRow("SELECT local_net_address FROM sys.dm_exec_connections WHERE session_id=@@SPID").Scan(&localNetAddr)
+	if err != nil {
+		t.Fatal("cannot scan local_net_address value", err)
+	}
+	if !localNetAddr.Valid {
```
Comment (shueybubbles) [inline tds_test.go]: this is not correct. local_net_address can be null particularly for non-tcp local connections.

**Review by shueybubbles — APPROVED** [review]
